# Generated by Django 5.1.6 on 2025-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reader",
            name="reader_password",
            field=models.CharField(
                default="defaultpassword", max_length=20, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reader",
            name="reference_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
