# Generated by Django 5.1.6 on 2025-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0002_reader_reader_password_alter_reader_reference_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=200, unique=True)),
                ("book_name", models.TextField()),
                ("book_author", models.TextField()),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
