# Generated by Django 5.1.6 on 2025-02-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0003_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="book_type",
            field=models.TextField(default="Fiction"),
            preserve_default=False,
        ),
    ]
