# Generated by Django 5.1.6 on 2025-02-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0008_alter_reader_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reader",
            name="user",
        ),
    ]
