# Generated by Django 5.1.6 on 2025-02-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0009_remove_reader_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="is_suggested",
            field=models.BooleanField(default=False),
        ),
    ]
